### ISSUE TITLE
转换之后的GIF不是循环

### ISSUE THREAD

**Issue by SakamotoCHN** [HoshiriAki/webm2gif#1]
播放一遍就结束了
![image](https://github.com/user-attachments/assets/7a220964-dea3-48d2-9443-a6a5446bddbc)

**Comment by HoshiriAki** [comment]
> 播放一遍就结束了
> ![image](https://github.com/user-attachments/assets/7a220964-dea3-48d2-9443-a6a5446bddbc)
> 
能把源文件发我一份吗？我测试一下有没有修好，感谢。邮箱：Hoshiriaki@outlook.com

**Comment by HoshiriAki** [comment]
> 播放一遍就结束了 ![image](https://private-user-images.githubusercontent.com/94337186/373833943-7a220964-dea3-48d2-9443-a6a5446bddbc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgxMDUxOTUsIm5iZiI6MTcyODEwNDg5NSwicGF0aCI6Ii85NDMzNzE4Ni8zNzM4MzM5NDMtN2EyMjA5NjQtZGVhMy00OGQyLTk0NDMtYTZhNTQ0NmJkZGJjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA1VDA1MDgxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRjNzJkODMzYTE0Yzg3MDc0NmYyZjc2MWI5ZGE0MTFlMTE3ODU1ZmI3YjljN2JkZWM3MjFkNmM3OTgxNDJmYzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.I2syYNRf1nYT3iBPhyxUYGtfCyoTgjNUolVgEf4mCMw)

已更新，问题应该解决了。

**Comment by SakamotoCHN** [comment]
已经解决了，感谢
